-- DROP TABLE IF EXISTS ACCOUNTS;
-- DROP TABLE IF EXISTS ATMS;

-- DROP TYPE IF EXISTS transaction_type;

-- DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TYPE transaction_type AS ENUM ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER');

CREATE TABLE ACCOUNTS (
  ID SERIAL ,
  BRANCH INT,
  ACCOUNT_NUMBER INT,
  VERIFICATION_DIGIT INT,
  NAME VARCHAR,
  CPF VARCHAR,
  ACCOUNT_TYPE INT,
  CARD_NUMBER VARCHAR,
  PASSWORD VARCHAR,
  BALANCE DOUBLE PRECISION,
  PRIMARY KEY (ID)
);

CREATE TABLE ATMS (
  ID SERIAL,
  LOCATION VARCHAR,
  BALANCE DOUBLE PRECISION,
  PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTIONS (
  ID SERIAL,
  ACCOUNT_ID INT,
  ATM_ID INT,
  DATE_TIME TIMESTAMP,
  TRANSACTION_TYPE transaction_type,
  VALUE DOUBLE PRECISION,
  LATITUDE FLOAT8 NULL,
  LONGITUDE FLOAT8 NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE TRANSACTIONS 
ADD CONSTRAINT TRANSACTIONS_ACCOUNT 
FOREIGN KEY (ACCOUNT_ID) 
REFERENCES ACCOUNTS (ID);

ALTER TABLE TRANSACTIONS 
ADD CONSTRAINT TRANSACTIONS_ATM 
FOREIGN KEY (ATM_ID) 
REFERENCES ATMS (ID);