-- DROP TABLE IF EXISTS CONTAS;
-- DROP TABLE IF EXISTS CAIXAS;

-- ALTER TABLE IF EXISTS TRANSACOES 
-- DROP CONSTRAINT TRANSACOES_CONTA;

-- ALTER TABLE IF EXISTS TRANSACOES 
-- DROP CONSTRAINT TRANSACOES_CAIXA;

-- DROP TABLE IF EXISTS TRANSACOES;

CREATE TABLE CONTAS (
  ID SERIAL ,
  AGENCIA INT,
  NUMERO_CONTA INT,
  DIGITO_VERIFICADOR INT,
  NOME VARCHAR,
  CPF VARCHAR,
  TIPO_CONTA INT,
  NUMERO_CARTAO VARCHAR,
  SENHA VARCHAR,
  SALDO DOUBLE PRECISION,
  PRIMARY KEY (ID)
);

CREATE TABLE CAIXAS (
  ID SERIAL,
  LOCALIZACAO VARCHAR,
  SALDO DOUBLE PRECISION,
  PRIMARY KEY (ID)
);

CREATE TABLE TRANSACOES (
  ID SERIAL,
  CONTA_ID INT,
  CAIXA_ID INT,
  DATA_HORA TIMESTAMP,
  TIPO_TRANSACAO CHAR,
  VALOR DOUBLE PRECISION,
  PRIMARY KEY (ID)
);

ALTER TABLE TRANSACOES 
ADD CONSTRAINT TRANSACOES_CONTA 
FOREIGN KEY (CONTA_ID) 
REFERENCES CONTAS (ID);

ALTER TABLE TRANSACOES 
ADD CONSTRAINT TRANSACOES_CAIXA 
FOREIGN KEY (CAIXA_ID) 
REFERENCES CAIXAS (ID);


ALTER TABLE PUBLIC.TRANSACOES 
ADD LATITUDE FLOAT8 NULL;


ALTER TABLE PUBLIC.TRANSACOES 
ADD LONGITUDE FLOAT8 NULL;